### ISSUE TITLE
help how to collect real data

### ISSUE THREAD

**Issue by Zhu0917** [LeCAR-Lab/anycar#2]
hello,your work is awesome,but i have a question that how to collect real data from my autonomous car to build the dynamics model,does it just use your real-collect python file under collect file folder,i see you write how to collect in simulator environment, thanks:)

**Comment by WENLIXIAO-CS** [comment]
Hi, thanks for pointing this out. The `real-collect` folder, which was used for a sanity check, is now deprecated. The latest pipeline for collecting real-world data is as follows:

1. Launch the `car_ros2` node by following [these instructions](https://github.com/LeCAR-Lab/anycar/blob/main/car_ros2/README.md).
2. Record a rosbag using `ros2 bag record -a -o YOUR-ROS-BAG-NAME`.
3. Process the recorded rosbag with [this script](https://github.com/LeCAR-Lab/anycar/blob/main/car_dynamics/car_dynamics/analysis/rosbag_to_dataset.py).
4. The dataset will be automatically stored under `car_foundation/car_foundation/data`.

**Comment by Zhu0917** [comment]
thanks for you good answer
