### ISSUE TITLE
transformer_engine_cu12 1.11.0 is not supported

### ISSUE THREAD

**Issue by zhenhangguo** [LeCAR-Lab/anycar#3]
Hello, your work is very excellent! During the process of reproducing it locally, i encountered an issue with the `transformer_engine` library not being compatible while setting up the environment. My CUDA version is 12.6, and Ubuntu version is 22.04, i also tried CUDA 12.4 and other versions of transformer_engine, but encountered similar issues.

**Comment by WENLIXIAO-CS** [comment]
Hello,

Thank you for your interest in this project and for your kind words!

I’m sorry to hear about the compatibility issues you’re encountering with the `transformer_engine` library. Here is the environment setup I’m currently using:

- **CUDA Version**: 12.4 (nvcc 12.4.131)
- **Ubuntu Version**: 22.04.4 LTS (Jammy)
- **Transformer Engine Version**: 1.7.0+4e7caa1

To help troubleshoot the issue, could you please try the following:

- Make sure your environment has the same CUDA version (12.4) that I have verified compatibility with.
- If you are using a different version of `transformer_engine`, you might try installing version `1.7.0+4e7caa1` to see if it resolves the issue.
- Verify the compatibility of the `transformer_engine` version you are using with CUDA 12.6. You can check the version using:
  ```bash
  pip show transformer_engine
  ```

If the issue persists after aligning these versions, please let me know the exact error message you encounter, and I will do my best to assist you further.

**Comment by zhenhangguo** [comment]
Hello, thank you very much for your support! I tried to install **Transformer Engine Version: 1.7.0+4e7caa1**, but found 1.7.0 is not available in the Python Package Index (PyPI). Only the following versions are available: 0.0.0, 1.9.0, 1.9.0.post1, 1.10.0, and 1.11.0. Also try install different version or compile directly  from source, but regardless of the method, when calling libtransformer_engine.so, I encounter the error 'undefined symbol: nvrtcGetCUBINSize'. It seems there is a conflict with nvrtc.
I will try to compile Transformer Engine Version: 1.7.0+4e7caa1 from source to see if it resolves the issue, since this version was not available, are there any other environment configurations that could work properly?

**Comment by zhenhangguo** [comment]
Try **Transformer Engine Version: 1.7.0+4e7caa1**,  also encounter the error 'undefined symbol: nvrtcGetCUBINSize'.

**Comment by zhenhangguo** [comment]
try use code source from transformer_engine instead of import, thanks a lot for support!
