### ISSUE TITLE
Release the models?

### ISSUE THREAD

**Issue by niciBume** [LeCAR-Lab/anycar#4]
Thanks a lot for sharing this code, the project looks awesome!

I could not find the trained models anywhere, perhaps I overlooked? If not, would it be possible to release the trained models? 

Thanks!

**Comment by WENLIXIAO-CS** [comment]
Hi,

Thank you so much for your interest in our project!

We have plans to organize and gradually release the model checkpoints. For now, we’ve provided an example checkpoint for the example task, which you can access [here on Hugging Face](https://huggingface.co/wenlixiao/anycar-sim-small/tree/main). We’ve also updated the instructions in the README to reflect this.

Thank you again, and feel free to reach out if you have any other questions or suggestions!
